/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.135}>
        <group position={[-0.262, -0.314, 4.671]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.Gums} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Gums} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Gums} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6002.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6003.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6004.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6005.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6006.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6007.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6008.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6009.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6010.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6011.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6012.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6013.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6014.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_6015.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7001.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7002.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7003.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7004.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7005.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7006.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7007.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7008.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7009.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7010.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7011.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7012.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7013.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7014.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7015.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7016.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7017.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7018.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7019.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Tongue} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/new.glb')
