/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [12.59KB] > /home/nevo/code/threejs/first-three/public/models/teeth/scene-transformed.glb [148.88KB] (-1083%)
Author: dewa (https://sketchfab.com/dewa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teeth-3a0fb31b9d864b27a0846aca8579461c
Title: Teeth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.Gums} position={[-1.084, 19.314, 1.298]} rotation={[-Math.PI / 2, 0, 0]} scale={4.135} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Teeth} position={[-1.084, 19.314, 1.298]} rotation={[-Math.PI / 2, 0, 0]} scale={4.135} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Tongue} position={[-1.084, 19.314, 1.298]} rotation={[-Math.PI / 2, 0, 0]} scale={4.135} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
